### PR TITLE
Test Doc Builds

### LINKED ISSUE #159: Integration Test for Doc Builds
There should be integration tests for testing doc builds.

### PR DESCRIPTION
**Pull request by jeff-hernandez**
Closes #159 by adding integration tests for doc builds.

### CODE REVIEW

**Comment by jeff-hernandez** [comment]
The docs take ~12 minutes to build on CircleCI. Locally, it takes about a minute. Not sure if this is a problem.

**Comment by jeff-hernandez** [comment]
Hmm, after updating the doc builds to treat warnings as errors, a [context deadline exceeded](https://app.circleci.com/pipelines/github/FeatureLabs/compose/1183/workflows/d32fddbb-d71a-4dcb-aa43-2190b1fec61a/jobs/3710/parallel-runs/0/steps/0-105) problem occurs on CircleCI.

**Comment by jeff-hernandez** [comment]
Found this on [CircleCI Support](https://support.circleci.com/hc/en-us/articles/360045268074-Build-Fails-with-Too-long-with-no-output-exceeded-10m0s-context-deadline-exceeded-):

> In CircleCI, a command will be killed if a certain period of time has passed with no output. By default, this is 10 minutes. This is designed to prevent errors in builds from hanging using a large number of credits unintentionally.

**Comment by rwedge** [comment]
I reran a previous commit on CircleCi and also got a timeout, so the warnings as errors may not be the issue.  It seems that a lot of time is being spent building the page on the fan degradation example

**Comment by jeff-hernandez** [comment]
On read the docs, the [latest build](https://readthedocs.com/projects/feature-labs-inc-compose/builds/401344/) that include the notebooks took ~6 minutes. On CircleCI, it took ~20 minutes.

**Comment by jeff-hernandez** [comment]
I'm thinking about using a smaller sample of data in the notebooks to speed up the doc builds on CircleCI .

**Comment by rwedge** [comment]
What if we tried using a time-based timeout for the EvalML search instead of number of pipelines?

**Comment by jeff-hernandez** [comment]
@rwedge sounds good, will try the time-based search.

**Comment by jeff-hernandez** [comment]
I didn't notice a difference in the doc builds after pinning the EvalML version or using a time-based search.

**Comment by jeff-hernandez** [comment]
The [latest build](https://app.circleci.com/pipelines/github/FeatureLabs/compose/1210/workflows/ae41bbf5-8f51-4fc5-ad9e-ac6e631ad39c/jobs/3874/parallel-runs/0/steps/0-105) on CircleCI with an additional notebook took ~37 minutes.

**Comment by jeff-hernandez** [comment]
The [latest build](https://app.circleci.com/pipelines/github/FeatureLabs/compose/1211/workflows/e66a56e4-9939-41d9-b68f-5d140eef47a8/jobs/3879/parallel-runs/0/steps/0-105) using smaller samples of data took ~28 minutes on CircleCI.

**Comment by jeff-hernandez** [comment]
After increasing the [resource class](https://circleci.com/docs/2.0/configuration-reference/#docker-executor) of the executor, the [latest build](https://app.circleci.com/pipelines/github/FeatureLabs/compose/1212/workflows/8194b52e-c378-4a25-b69c-79a3414bf39d/jobs/3883/parallel-runs/0/steps/0-105) took ~11 minutes.

**Comment by jeff-hernandez** [comment]
I tried running the notebooks before the doc build at runtime. The [build](https://app.circleci.com/pipelines/github/FeatureLabs/compose/1214/workflows/6b75733a-7580-45c8-a4f9-aba3f21f6968/jobs/3900/parallel-runs/0/steps/0-105) took ~7 minutes.

**Comment by jeff-hernandez** [comment]
After limiting the search by model type, the [build](https://app.circleci.com/pipelines/github/FeatureLabs/compose/1221/workflows/4f3e0eb9-f3a1-4df1-8874-bc5099e1aef4/jobs/3946/parallel-runs/0/steps/0-105) took a minute!

**Review by rwedge — APPROVED** [review]
Looks good

**Pull request merged**
